"""Metric explanations for Lynx Communication Services Analysis."""

from __future__ import annotations
from lynx_comm.models import MetricExplanation

METRIC_EXPLANATIONS: dict[str, MetricExplanation] = {}

def _add(key, full_name, description, why_used, formula, category):
    METRIC_EXPLANATIONS[key] = MetricExplanation(key=key, full_name=full_name, description=description,
                                                  why_used=why_used, formula=formula, category=category)

# ── Valuation ──────────────────────────────────────────────────────
_add("pe_trailing", "Price-to-Earnings (TTM)", "Compares stock price to trailing 12-month earnings per share.", "Anchor for mature carriers, broadcasters, ad agencies, and profitable internet platforms. Less meaningful for streaming-pure players still scaling content amortization.", "P/E = Price / EPS (TTM)", "valuation")
_add("pe_forward", "Forward P/E", "Forward P/E based on next-year analyst EPS estimates.", "Useful for streaming platforms ramping into operating leverage, or carriers exiting a heavy capex cycle.", "Fwd P/E = Price / Est. EPS (next FY)", "valuation")
_add("pb_ratio", "Price-to-Book", "Compares stock price to book value per share.", "Less informative for asset-light internet platforms; more useful for telecom and cable carriers with heavy network/spectrum on the balance sheet.", "P/B = Price / Book Value per Share", "valuation")
_add("ps_ratio", "Price-to-Sales", "Compares market cap to revenue.", "Useful for sub-scale streaming or social platforms before profitability inflection. Benchmarks: Telecom 1-2x; cable 1-2x; broadcasting 1-3x; internet platforms 4-8x; ad-tech 5-12x at growth.", "P/S = Market Cap / Revenue", "valuation")
_add("p_fcf", "Price-to-Free-Cash-Flow", "Compares market cap to free cash flow.", "The dominant cash-economics anchor for mature carriers, internet platforms (GOOGL, META) and cable operators that distribute heavy free cash flow.", "P/FCF = Market Cap / FCF", "valuation")
_add("ev_ebitda", "Enterprise Value / EBITDA", "Capital-structure-neutral earnings multiple.", "The dominant comm-services valuation lens. Telecom/cable: 6-9x. Internet platforms: 12-18x. Streaming-pure: 15-25x at growth, 8-15x mature.", "EV/EBITDA = (Market Cap + Debt - Cash) / EBITDA", "valuation")
_add("ev_revenue", "Enterprise Value / Revenue", "EV divided by revenue.", "Useful when EBITDA is depressed by content amortization (legacy media) or capex (5G build). Streaming growth: 3-6x; mature 1-3x.", "EV/Revenue = EV / Revenue", "valuation")
_add("ev_gross_profit", "EV / Gross Profit", "EV divided by gross profit — a margin-adjusted variant of EV/Sales.", "Cleaner cross-comparison between hardware-heavy carriers and asset-light internet platforms. Strips equipment-resale dilution from telecom revenue.", "EV / GP = EV / (Revenue - COGS)", "valuation")
_add("ev_to_arr", "EV / ARR (Subscription)", "Enterprise value divided by annualized recurring subscription revenue.", "Native lens for streaming and other subscription-driven comm services. Approximated when ARR isn't disclosed (revenue + Δdeferred). Growth-streaming: 5-12x; mature 3-6x.", "EV/ARR = EV / (Subscription rev + Δdeferred rev)", "valuation")
_add("ev_to_subscriber", "EV per Subscriber", "Enterprise value divided by total subscribers.", "The classic telecom/cable/streaming valuation lens. Wireless: $1,500-3,000/sub. Cable broadband: $4,000-7,000/sub. Streaming: $200-700/sub.", "EV / Total Subscribers", "valuation")
_add("ev_per_employee", "EV per Employee", "Enterprise value divided by full-time employees.", "Productivity check. Internet platforms run >$5M/employee; carriers $500k-1.5M; agencies $200-400k.", "EV / Employees", "valuation")
_add("ev_to_ebitda_capex_adj", "EV / (EBITDA - Capex)", "Capex-adjusted EBITDA multiple — the 'real' EBITDA after maintaining the network.", "Critical correction for telecom/cable. Reported EV/EBITDA looks cheap, but EV/(EBITDA-capex) reveals true cash economics during a heavy capex cycle.", "EV / (EBITDA - Maintenance Capex)", "valuation")
_add("fcf_yield", "FCF Yield", "Free cash flow / market cap — inverse of P/FCF.", "Anchor for mature carriers and large-cap platforms. Carriers/cable target 5-9%; internet platforms 3-6%; streaming-growth often <3% or negative.", "FCF Yield = FCF / Market Cap", "valuation")
_add("price_per_dau", "Market Cap per DAU", "Market cap divided by daily active users.", "Engagement-anchored lens for social/internet (Meta, Snap, Reddit, Pinterest). High-monetization platforms (Meta) >$700/DAU; lower-ARPU peers <$100.", "Market Cap / DAU", "valuation")
_add("rule_of_40_adj_multiple", "R40-Adjusted EV/Revenue", "EV/Revenue divided by Rule-of-40 sum normalized to 40.", "Normalizes valuation by quality of growth + profitability — fair cross-cohort comparison for streaming/internet subsegments.", "EV/Rev / (Rule40 / 40)", "valuation")
_add("peg_ratio", "PEG Ratio", "P/E adjusted by growth rate.", "Useful for mature internet platforms with durable double-digit growth. PEG <1 suggests undervaluation vs growth.", "PEG = P/E / Annual EPS growth rate", "valuation")
_add("cash_to_market_cap", "Cash / Market Cap", "How much of market cap is backed by cash on the balance sheet.", "Less common in comm services (most are leveraged), but relevant for cash-rich internet platforms (GOOGL, META historically).", "Cash / Market Cap", "valuation")

# ── Profitability ──────────────────────────────────────────────────
_add("roe", "Return on Equity", "Profit per dollar of equity.", "For mature carriers and platforms, ROE >15% signals strong profitability and disciplined capital allocation.", "ROE = Net Income / Equity", "profitability")
_add("roic", "Return on Invested Capital", "Return on all invested capital.", "The cleanest moat evidence for capex-heavy carriers and content-heavy media. >12% sustained = high quality.", "ROIC = NOPAT / Invested Capital", "profitability")
_add("gross_margin", "Gross Margin", "Revenue remaining after cost of revenue.", "Sub-sector defining: Internet platforms 50-60%; streaming 40-55%; carriers 50-65% (network-cost driven); cable 65-70% (broadband heavy); broadcasting 30-40%.", "Gross Margin = (Revenue - COGS) / Revenue", "profitability")
_add("operating_margin", "Operating Margin", "Revenue remaining after all operating expenses.", "Benchmark by sub-sector: Internet platforms >25%; mature carriers 18-25%; streaming-pure target >20%; legacy media 5-15%; ad agencies 14-18%.", "Operating Margin = Operating Income / Revenue", "profitability")
_add("operating_margin_ex_content", "Operating Margin (ex-Content Amort)", "Operating margin excluding content amortization expense.", "Crucial for streaming/media — strips out the heavy non-cash content amort to expose underlying operating economics.", "(Op Inc + Content Amort) / Revenue", "profitability")
_add("net_margin", "Net Margin", "Bottom-line profitability.", "Traditional anchor; distorted in carriers by interest expense (high leverage) and in media by content amort.", "Net Margin = Net Income / Revenue", "profitability")
_add("fcf_margin", "FCF Margin", "Free cash flow as % of revenue.", "The truest profitability metric for capex-heavy carriers and content-heavy media. Mature carriers 12-18%; internet platforms >20%; streaming target 10%+.", "FCF Margin = FCF / Revenue", "profitability")
_add("ebitda_margin", "EBITDA Margin", "EBITDA / revenue.", "Carrier benchmark: 35-45%. Cable: 35-45%. Internet platforms: 35-55%. Streaming: 20-30%. Broadcasting: 25-35%.", "EBITDA Margin = EBITDA / Revenue", "profitability")
_add("rule_of_40", "Rule of 40 (FCF variant)", "Revenue growth % + FCF margin %.", "Quality gate for digital comm services (streaming, internet platforms). >40% passing, >60% best-in-class. Less applicable to mature carriers.", "Rule40 = Rev Growth % + FCF Margin %", "profitability")
_add("rule_of_40_ebitda", "Rule of 40 (EBITDA variant)", "Revenue growth % + EBITDA margin %.", "Useful for sub-scale streaming/social pre-FCF — tracks the same trade-off vs EBITDA.", "Rule40(EBITDA) = Rev Growth % + EBITDA Margin %", "profitability")
_add("arpu", "ARPU (Average Revenue Per User)", "Service revenue divided by average subscribers/users.", "THE canonical comm-services metric. Wireless postpaid: $40-60/mo. Cable broadband: $60-80/mo. Streaming: $7-16/mo. Social ad ARPU varies $5-200+/yr by region.", "ARPU = Service Revenue / Avg Subscribers", "profitability")
_add("arpu_growth_yoy", "ARPU Growth (YoY)", "Year-over-year change in ARPU.", "Pricing power signal. Positive ARPU growth at flat-to-positive subs = quality. Falling ARPU + flat subs = competitive pressure.", "(ARPU - ARPU_Prior) / ARPU_Prior", "profitability")
_add("content_amort_intensity", "Content Amortization Intensity", "Content amortization expense / revenue.", "Critical for streaming/media. Netflix runs ~50%; legacy studios 30-45%; <30% may signal content under-investment in streaming.", "Content Amortization / Revenue", "profitability")
_add("content_roi", "Content ROI", "Streaming/media revenue per dollar of amortized content.", "Hit-rate indicator. >2.0x indicates strong content economics; <1.5x signals over-investment or weak monetization.", "(Content Revenue) / Content Amortization", "profitability")
_add("advertising_revenue_pct", "Advertising Revenue %", "Ad revenue as % of total revenue.", "Cyclicality proxy. >70% ad-driven = highly cyclical (Meta, GOOGL, broadcasters). Mix shift to subscription reduces beta.", "Ad Revenue / Total Revenue", "profitability")
_add("subscription_revenue_pct", "Subscription Revenue %", "Recurring subscription revenue as % of total.", "Predictability proxy. >60% subscription = stable; mix toward subscription is a quality positive in streaming/internet.", "Subscription Revenue / Total Revenue", "profitability")
_add("magic_number", "Magic Number", "Sales efficiency: (ΔRevenue × 4) / S&M spend.", "Useful for digital subsectors. >1 = invest more in S&M; <0.5 = fix the motion before scaling.", "Magic Number = (ΔRevenue × 4) / S&M", "profitability")
_add("sbc_to_revenue", "SBC / Revenue", "Stock-Based Compensation as % of revenue.", "Internet/social/gaming heavy SBC users (often 10-25% revenue). Carriers and agencies near zero. Watch for concentration in tech-leaning subsegments.", "SBC / Revenue", "profitability")
_add("sbc_to_fcf", "SBC / FCF", "SBC as % of free cash flow.", "Truer dilution picture — if SBC > FCF, FCF is partly paper. Common in growth-stage social/UGC platforms.", "SBC / FCF", "profitability")
_add("gaap_vs_adj_gap", "GAAP vs Adjusted Gap", "Spread between GAAP and non-GAAP operating income.", "Large gap = aggressive adjusted metrics. Common in streaming/social — review what's being excluded (SBC, restructuring, content writedowns).", "(Adj Op Inc - GAAP Op Inc) / Revenue", "profitability")

# ── Solvency ───────────────────────────────────────────────────────
_add("debt_to_equity", "Debt / Equity", "Debt vs equity financing.", "Comm services runs leveraged. Carriers/cable 1.0-2.5x normal; internet platforms <0.5x. >3x = refinancing risk in rising-rate environments.", "D/E = Total Debt / Equity", "solvency")
_add("debt_to_ebitda", "Debt / EBITDA (Gross)", "Gross leverage measured against earnings.", "Telecom/cable target <3.5x; >5x = stressed. Internet platforms typically <1x.", "Total Debt / EBITDA", "solvency")
_add("net_debt_to_ebitda", "Net Debt / EBITDA", "Net leverage measured against earnings — most-watched leverage metric in carriers/cable.", "Investment-grade carriers target <3.0x. >4.0x = high yield territory; rating actions below 4.5x. Critical for dividend coverage analysis.", "(Total Debt - Cash) / EBITDA", "solvency")
_add("current_ratio", "Current Ratio", "Short-term asset coverage.", ">1.0 healthy for working-capital-light carriers and platforms.", "Current Ratio = Current Assets / Current Liabilities", "solvency")
_add("interest_coverage", "Interest Coverage", "Ability to pay interest from operating income.", ">5x healthy for carriers; <3x = stressed; <2x = distressed (review refinancing).", "Operating Income / Interest Expense", "solvency")
_add("altman_z_score", "Altman Z-Score", "Bankruptcy probability predictor.", "Z >2.99: Safe. 1.81-2.99: Grey. <1.81: Distress. Less applicable to internet platforms; relevant for stressed media/broadcasting.", "Z = 1.2(WC/TA) + 1.4(RE/TA) + 3.3(EBIT/TA) + 0.6(MV/TL) + 1.0(Sales/TA)", "solvency")
_add("cash_burn_rate", "Cash Burn Rate", "Annual rate of cash consumption.", "Critical for pre-FCF streaming or sub-scale social platforms. Determines runway to FCF positivity.", "Operating Cash Flow (negative)", "solvency")
_add("cash_runway_years", "Cash Runway", "Years of operation at current burn rate.", "<1yr = imminent financing. >3yr = comfortable. Most public comm-services names are FCF-positive; this matters for sub-scale challengers.", "Total Cash / Annual Burn", "solvency")
_add("burn_as_pct_of_market_cap", "Burn % of Market Cap", "Burn as a fraction of equity value.", "<5%/yr healthy; >10%/yr is a serious dilution setup.", "|Burn| / Market Cap", "solvency")
_add("capex_to_revenue", "Capex / Revenue", "Capital intensity.", "Defining sub-sector marker. Carriers 15-25% during 5G build; cable 10-15%; internet platforms 15-25% (AI infra ramp); streaming 5-10%; agencies <2%.", "Capex / Revenue", "solvency")
_add("capex_to_subscriber", "Capex per Subscriber", "Annual capex per subscriber.", "Network-investment efficiency for telecom/cable. Wireless carriers $80-150/sub/yr; cable $200-300/sub/yr; spikes during fiber/5G builds.", "Annual Capex / Total Subscribers", "solvency")
_add("spectrum_license_book_value", "Spectrum / FCC License Book Value", "Net book value of spectrum and broadcast licenses.", "Material indefinite-lived intangible for wireless carriers and broadcasters. Auctions and reallocations move this; Verizon/AT&T spectrum auctions ran $80B+ in C-band.", "Balance sheet — indefinite-lived intangible", "solvency")
_add("content_obligations", "Content Obligations (Off-Balance)", "Off-balance-sheet content commitments — sports rights, output deals, future programming.", "Critical for streaming/media. Multi-year sports rights ($100B+ at NFL) or output deals can dwarf reported leverage.", "Disclosed in 10-K commitments footnote", "solvency")
_add("rpo_coverage", "RPO / Revenue Coverage", "Remaining Performance Obligations vs annual revenue.", "Forward-visibility proxy for B2B-heavy comm-services (cloud, business voice, advertising commitments).", "RPO / Revenue", "solvency")
_add("deferred_revenue_ratio", "Deferred Revenue Ratio", "Deferred revenue vs annual revenue.", "Subscription billing strength. Higher = stronger forward subscription visibility (streaming, business communications).", "Deferred Revenue / Revenue", "solvency")
_add("goodwill_to_assets", "Goodwill / Total Assets", "Goodwill from acquisitions as share of assets.", ">40% is impairment-risk territory. Comm services has been M&A-heavy (T+TWX, CMCSA+SKY, etc.) — many large goodwill impairments in cycles.", "Goodwill / Total Assets", "solvency")

# ── Growth ─────────────────────────────────────────────────────────
_add("revenue_growth_yoy", "Revenue Growth (YoY)", "Annual revenue change.", "Carriers low single-digit; streaming high-teens at growth; internet platforms 8-20%; agencies low single-digit; gaming hit-driven.", "(Rev - Rev_Prior) / |Rev_Prior|", "growth")
_add("revenue_cagr_3y", "Revenue CAGR (3Y)", "3-year compound revenue growth.", "Smooths content release / political cycle / FX noise. >15% impressive; <3% mature.", "CAGR = (End / Start)^(1/3) - 1", "growth")
_add("earnings_growth_yoy", "Earnings Growth (YoY)", "Annual net income change.", "Drives mature platform valuation. In carriers, distorted by tower-deal gains/losses; in streaming by content writedowns.", "(NI - NI_Prior) / |NI_Prior|", "growth")
_add("shares_growth_yoy", "Share Dilution (YoY)", "Annual change in shares outstanding.", "Carriers/cable usually buying back shares (negative growth). Internet/social/gaming dilute via SBC: <3% acceptable, >6% concerning.", "(Shares - Shares_Prior) / Shares_Prior", "growth")
_add("subscribers", "Total Subscribers", "Total paying subscribers/users.", "Foundation metric. Direction (growing vs shrinking) often matters more than absolute level.", "Disclosed in operational KPIs", "growth")
_add("subscriber_net_adds", "Subscriber Net Adds", "Net new subs added in period (gross adds minus disconnects).", "The leading indicator. Wireless: postpaid phone net adds drive valuation. Streaming: net adds by region drive multiple. Cable: broadband net adds.", "Period gross adds - period disconnects", "growth")
_add("subscriber_growth_yoy", "Subscriber Growth (YoY)", "YoY change in total subscribers.", "Best for comparing growth-stage streaming and emerging-market carriers. Mature-market wireless growth runs <2%.", "(Subs - Subs_Prior) / Subs_Prior", "growth")
_add("mau", "Monthly Active Users (MAU)", "Unique users active in the past month.", "Reach metric for internet platforms / social media. MAU trajectory is a primary thesis variable for ad-supported platforms.", "Disclosed in earnings reports", "growth")
_add("dau", "Daily Active Users (DAU)", "Unique users active daily.", "Engagement metric. Higher DAU = more ad inventory and stickier user base. Critical for Meta, Snap, Pinterest, Reddit.", "Disclosed in earnings reports", "growth")
_add("dau_mau_ratio", "DAU / MAU (Engagement)", "Daily-to-monthly active user ratio.", "Engagement quality benchmark. >65% = highly engaged. Meta Family of Apps ~70%+; Snap mid-50s; Reddit lower.", "DAU / MAU", "growth")
_add("arr_growth_yoy", "ARR / Subscription Growth (YoY)", "Annual Recurring (subscription) Revenue growth.", "True signal for streaming/digital subscription comm services. Approximated as subscription revenue growth when ARR isn't disclosed.", "(ARR - ARR_Prior) / ARR_Prior", "growth")
_add("net_revenue_retention", "Net Revenue Retention", "% of cohort revenue retained after expansion & churn.", "Where disclosed (B2B comm-services, business voice, ad-tech). >100% = expansion economy.", "(Starting + Expansion - Contraction - Churn) / Starting", "growth")
_add("gross_revenue_retention", "Gross Revenue Retention", "% of cohort revenue retained before expansion.", "Pure retention signal. >90% sticky; <80% product-market-fit risk.", "(Starting - Contraction - Churn) / Starting", "growth")
_add("content_intensity", "Content Investment Intensity", "Content investment / revenue (cash basis).", "Streaming/media defining metric. Netflix/Disney run 35-50%; pure-streaming peers higher in build-out phase.", "Cash content spend / Revenue", "growth")
_add("content_growth_yoy", "Content Spend Growth (YoY)", "YoY change in content investment.", "Investment trajectory signal. Decel = harvest mode; accel = competitive escalation (cost positive for content rights holders).", "(Content - Content_Prior) / Content_Prior", "growth")
_add("rd_intensity", "R&D Intensity", "R&D as % of revenue.", "Internet content & gaming run 10-25%; streaming 8-15% (tech infra); carriers <2%; agencies <1%.", "R&D / Revenue", "growth")
_add("rd_growth_yoy", "R&D Growth (YoY)", "Year-over-year R&D spending change.", "Signals platform investment cadence (AI capex, ad tooling, network engineering).", "(R&D - R&D_Prior) / R&D_Prior", "growth")
_add("sales_marketing_intensity", "S&M Intensity", "Sales & marketing as % of revenue.", "Streaming-growth runs 15-25%; mature platforms 10-15%; carriers 12-15% (subscriber acquisition heavy); agencies passthrough.", "S&M / Revenue", "growth")
_add("cost_per_gross_add", "Cost per Gross Add (CPGA)", "S&M (and equipment subsidy) cost per gross subscriber addition.", "Telecom/streaming subscriber acquisition efficiency. Wireless typically $300-500/gross add; streaming $50-150.", "(S&M + Subsidies) / Gross Adds", "growth")
_add("advertising_revenue_growth_yoy", "Ad Revenue Growth (YoY)", "Year-over-year advertising revenue growth.", "Cyclicality and pricing-power signal. Ad cycle reversals can be -10 to -20% YoY (e.g. 2022).", "(Ad Rev - Ad Rev_Prior) / Ad Rev_Prior", "growth")
_add("employee_growth_yoy", "Employee Growth (YoY)", "Headcount change.", "Carriers stable to declining (efficiency push); internet/streaming hiring during AI/content cycles. Watch productivity.", "(Emp - Emp_Prior) / Emp_Prior", "growth")
_add("revenue_per_employee", "Revenue per Employee", "Productivity metric.", "Internet platforms $1.5-3M; carriers $400-800k; streaming $700k-1.5M; agencies $200-400k.", "Revenue / Employees", "growth")
_add("revenue_per_subscriber", "Revenue per Subscriber", "Total revenue per sub (often equals or exceeds ARPU when including equipment/ads).", "Cross-sub-sector productivity check.", "Revenue / Total Subscribers", "growth")

# ── Sector Quality ─────────────────────────────────────────────────
_add("quality_score", "Sector Quality Score", "Composite Communication-Services quality score (0-100).", "Weighted: Moat (20), Subscriber/Engagement quality (20), Financial Position/Leverage (15), Capex/Content discipline (10), Dilution/SBC (10), Unit Economics (15), Revenue Predictability (10). >75 elite, <30 weak.", "Weighted sum across 7 axes", "comm_quality")
_add("moat_assessment", "Moat Assessment", "Qualitative moat classification.", "Network effects (social), spectrum/fiber (carriers), content library (streaming), switching costs (carriers/cable), brand & franchise IP (gaming/media).", "Derived from sub-sector + GM + scale", "comm_quality")
_add("network_quality_assessment", "Network Quality Assessment", "Network footprint, spectrum holdings, fiber penetration, 5G coverage.", "Differentiator for telecom/cable. T-Mobile mid-band lead vs Verizon C-band depth — drove subscriber outperformance.", "Derived from operational disclosures", "comm_quality")
_add("content_library_assessment", "Content Library Assessment", "Depth, IP ownership, library breadth and exclusivity.", "Streaming/media defining moat. Disney+Marvel+Pixar, Netflix originals, WBD library — inversely related to needed content investment.", "Derived from content spend + IP disclosures", "comm_quality")
_add("user_engagement_assessment", "User Engagement Assessment", "DAU/MAU ratio, time-spent, retention.", "Social/internet defining moat. Higher engagement = ad pricing power and platform durability.", "DAU/MAU + qualitative read", "comm_quality")
_add("leverage_assessment", "Leverage Assessment", "Net debt/EBITDA + interest coverage classification.", "Critical for telecom/cable/media. Investment-grade vs high-yield divide is at ~3.5-4.0x net debt/EBITDA.", "Net Debt / EBITDA band", "comm_quality")
_add("capex_cycle_assessment", "Capex Cycle Assessment", "Position in network/content investment cycle (build vs harvest).", "Carriers in 5G build (peak capex) vs harvest (FCF expansion). Streaming in content build vs library leverage.", "Trend in capex/revenue + content/revenue", "comm_quality")
_add("rule_of_40_assessment", "Rule-of-40 Verdict", "Pass/fail grade for digital subsegments.", "Applies to streaming, internet platforms, social, and growth-stage gaming. Less applicable to carriers/agencies/broadcasters.", "Rule40 band", "comm_quality")
_add("unit_economics", "Unit Economics", "Summary of ARPU, churn, CPGA.", "Sustainable subscriber economics: low churn × high ARPU × controlled CPGA = compounding. Negative on any axis = thesis risk.", "ARPU, Churn, CPGA composite", "comm_quality")
_add("sbc_risk_assessment", "SBC Risk", "Stock-based compensation risk framing.", "Concentrated in internet/social/gaming. Mature carriers and agencies near zero. Categories: Contained / Moderate / High / Severe.", "SBC / Revenue band", "comm_quality")
_add("platform_position", "Platform Position", "Scale/network/ecosystem position.", "Big Internet (GOOGL, META) and tier-1 carriers (TMUS, VZ) compound for decades. Sub-scale challengers face structural pressure.", "Tier + sub-sector + market share", "comm_quality")
_add("founder_led", "Founder-Led Signal", "Founder or strong insider control.", "Common in internet/social/gaming (Zuckerberg, Brin/Page, Pichai-team, Huffman, Sweeney). >10% insider ownership signals alignment.", "Insider ownership % band", "comm_quality")
_add("revenue_predictability", "Revenue Predictability", "Subscription/contract mix vs ad-cyclical.", ">60% subscription = predictable (carriers, streaming-mature, cable broadband). >70% ad = cyclical (Meta, GOOGL, broadcasters).", "Revenue mix decomposition", "comm_quality")

# ── Share Structure ────────────────────────────────────────────────
_add("shares_outstanding", "Shares Outstanding", "Basic shares currently issued.", "Baseline for per-share metrics. Mature carriers/cable typically buying back shares; growth-stage social/UGC dilute via SBC.", "—", "share_structure")
_add("fully_diluted_shares", "Fully Diluted Shares", "Shares + RSUs + options + warrants.", "True dilution floor. Particularly important for SBC-heavy social/UGC names (Roblox, Snap, Pinterest).", "Basic + RSUs + Options + Warrants", "share_structure")
_add("insider_ownership_pct", "Insider Ownership %", "% of shares held by insiders/founders.", ">10% = meaningful alignment (common in founder-led internet/social/gaming). Carriers and agencies typically <3%.", "Insider Shares / Total Shares", "share_structure")
_add("dual_class_structure", "Dual-Class Structure", "Whether insiders hold super-voting shares.", "Common in Communication Services (Meta, Alphabet, NYT, Liberty Media, NWSA). Locks in founder/family control — governance trade-off.", "Voting class structure", "share_structure")
_add("sbc_overhang_risk", "SBC Overhang Risk", "Forward dilution pressure from future equity comp grants.", "Severe in growth-stage social/UGC/gaming. Mature carriers and agencies have minimal overhang.", "Cumulative SBC run-rate vs float", "share_structure")

# ── Efficiency ─────────────────────────────────────────────────────
_add("rule_of_x_score", "Rule of X (Altimeter)", "Revenue growth × (1 + FCF margin).", "Multiplicative refinement of Rule-of-40. Useful for streaming/internet — emphasizes compounding of growth × profitability.", "Growth × (1 + FCF margin)", "efficiency")
_add("cac_payback_months", "Subscriber Acquisition Payback (months)", "Months to recover subscriber acquisition cost via gross profit.", "Wireless target <18 months; streaming target <8 months; >36 months = subscriber acquisition motion needs fixing.", "(S&M + Subsidies) / (Quarterly GP per sub × 3)", "efficiency")
_add("churn_rate_annual", "Annual Churn Rate", "Annualized subscriber churn (lower is better).", "Wireless postpaid phone churn <1.0% best-in-class; streaming 30-50%/yr typical; cable broadband 1.5-2.0%/mo.", "Disconnects / Avg Subscribers (annualized)", "efficiency")
_add("arpu_to_cpga_ratio", "ARPU / CPGA Ratio", "ARPU divided by Cost Per Gross Add — LTV/CAC proxy.", "Subscriber-economics LTV/CAC. >12 months of ARPU recovers CPGA = healthy. <6 months = subscriber economics under pressure.", "Annual ARPU / CPGA", "efficiency")
_add("fcf_conversion", "FCF Conversion", "FCF divided by net income.", ">1 = high-quality earnings (typical for mature platforms harvesting working capital). <0.8 = earnings overstating cash (common in growth-streaming).", "FCF / Net Income", "efficiency")

SECTION_EXPLANATIONS = {
    "profile": {"title": "Company Profile", "description": "Company identification, market cap tier, Communication Services lifecycle stage, sub-sector classification (Wireless / Cable / Streaming / Internet / Social / Advertising / Gaming / Publishing / Broadcasting), and jurisdiction risk."},
    "valuation": {"title": "Valuation Metrics", "description": "Traditional + sector-specific valuation ratios. EV/Subscriber and EV/(EBITDA-Capex) for telecom/cable; EV/Gross-Profit and FCF Yield for internet platforms; EV/ARR and EV/Subscriber for streaming; Price/DAU for social."},
    "profitability": {"title": "Profitability Metrics", "description": "Margin analysis plus comm-services-specific: ARPU, ARPU growth, content amortization intensity, content ROI, operating margin ex-content, ad/subscription revenue mix, Rule-of-40, SBC drag."},
    "solvency": {"title": "Solvency & Survival", "description": "Balance-sheet strength tilted to the leverage-heavy carrier/cable model: Net Debt/EBITDA, interest coverage, capex/sub, spectrum book value, off-balance content obligations. Plus the universal cash, runway, and goodwill/M&A risk checks."},
    "growth": {"title": "Growth & Engagement", "description": "Subscriber net adds, churn, ARPU growth, MAU/DAU engagement, content/ad/subscription revenue growth, R&D & content intensity, productivity. Designed around the operational KPIs comm-services management actually reports."},
    "share_structure": {"title": "Share Structure", "description": "Basic/fully-diluted shares, insider & institutional ownership, dual-class flag (common in this sector), SBC overhang risk for social/UGC/gaming subsegments."},
    "comm_quality": {"title": "Sector Quality Assessment", "description": "Communication-Services-specialized scoring. Evaluates moat type (network/spectrum/content/engagement), capex cycle position, leverage, unit economics (ARPU/Churn/CPGA), revenue predictability, and dilution/SBC risk."},
    "intrinsic_value": {"title": "Intrinsic Value Estimates", "description": "Methods adapted by sub-sector. Carriers/Cable: DCF + EV/(EBITDA-capex) peer multiples + dividend discount. Internet platforms: DCF + FCF yield. Streaming: EV/Subscriber + EV/ARR peer comp. Reverse DCF backs out market-implied growth."},
    "conclusion": {"title": "Assessment Conclusion", "description": "Weighted scoring across 5 categories with weights adapted by tier AND Communication Services lifecycle stage. Includes a 10-point sector screening checklist evaluating ARPU, churn, leverage, capex discipline, content economics, and platform/network moats."},
}

CONCLUSION_METHODOLOGY = {
    "overall": {"title": "Conclusion Methodology", "description": "Score is a weighted average of 5 categories (valuation, profitability, solvency, growth, sector quality). Weights vary by company tier AND Communication Services lifecycle stage. Mature carriers weight solvency (leverage) and FCF heavily; growth-stage streaming weights growth and unit economics; internet platforms balance growth, profitability, and quality. Verdicts: Strong Buy (>=75), Buy (>=60), Hold (>=45), Caution (>=30), Avoid (<30)."},
    "valuation": {"title": "Valuation Score", "description": "Starts at 50. Adjusted by EV/EBITDA (vs sub-sector benchmark), FCF yield, P/FCF, EV/Subscriber where applicable, EV/(EBITDA-capex) for capex-heavy carriers, P/E for mature names."},
    "profitability": {"title": "Profitability Score", "description": "Starts at 50. ARPU trajectory, gross/operating/FCF margin vs sub-sector benchmark, content amortization intensity, Rule-of-40 (digital subsegments), SBC penalty (internet/social/gaming)."},
    "solvency": {"title": "Solvency Score", "description": "Starts at 50. Net Debt/EBITDA (sector-critical), interest coverage, capex discipline (capex/revenue + capex/subscriber), goodwill/assets, off-balance content obligations. Carriers and cable evaluated against high-leverage peer norms."},
    "comm_quality": {"title": "Sector Quality Score", "description": "Composite of moat (20pts: network/content/engagement), Rule-of-40 (digital) or capex cycle (carriers) (20pts), financial position/leverage (15pts), dilution/SBC risk (10pts), capex/content discipline (10pts), unit economics: ARPU/Churn/CPGA (15pts), revenue predictability (10pts)."},
}

def get_explanation(key): return METRIC_EXPLANATIONS.get(key)
def get_section_explanation(section): return SECTION_EXPLANATIONS.get(section)
def get_conclusion_explanation(category=None): return CONCLUSION_METHODOLOGY.get(category or "overall")
def list_metrics(category=None):
    metrics = list(METRIC_EXPLANATIONS.values())
    return [m for m in metrics if m.category == category] if category else metrics
